<script lang="ts">
	import type { PageData } from './$types';
	import type { SvelteComponentTyped } from 'svelte/internal';
	import MainHeader from '../../../components/header/MainHeader.svelte';

	// Get data from SSR process
	// The data contains the page component.
	export let data: PageData;
	type IComponent = $$Generic<typeof SvelteComponentTyped<any, any, any>>;
	const component = data.component as unknown as IComponent;
</script>

<!-- NAVBAR -->
<header>
	<MainHeader active={1} />
</header>

<main>
	<!-- DYNAMIC COMPONENTS GENERATED BY MDSVEX  -->
	<div class="py-8 px-16">
		<svelte:component this={component} />
	</div>
</main>
